import { searchMeta, siteUrl, creativeBio, officialProfiles } from '../src/seo-data.js';
import { creativeServices } from '../src/services-data.js';
import { featuredProjects, galleryMedia, webProjects } from '../src/portfolio-data.js';
import { privacySections, privacyProviders, privacyUpdated } from '../src/privacy-content.js';
const link = (label, path) => `[${label}](${path.startsWith('/') ? siteUrl + path : path})`;
const profiles = officialProfiles.map(p => `- ${link(p.label, p.url)}`).join('\n');
const services = creativeServices.map(s => `- ${link(s.name, `/work/${s.id}/`)}: ${s.description}`).join('\n');
const projects = featuredProjects.map(p => `- ${p.title} — ${p.category}`).join('\n');
export const contactMarkdown = `# Contact Aashish Mahato\n\nI am based in Kathmandu, Nepal. Contact me about filmmaking, editing, photography, motion graphics, brand identity, graphic design, interface design, and web development.\n\n## Start a project enquiry\n\nSend a message through my official ${link('Instagram', officialProfiles[0].url)} or ${link('LinkedIn', officialProfiles[2].url)} profile. Explain what you want to make, who it is for, your project scope, deadline, and budget. Include relevant references or examples so we can discuss the direction and deliverables. Availability, pricing, and delivery dates must be confirmed directly with me; this website does not book work or take payment.\n\n## Before contacting me\n\nExplore ${link('Work', '/work/')} for selected projects, ${link('Gallery', '/gallery/')} for visual examples, and ${link('About', '/about/')} for my background. Please do not send passwords or sensitive personal information in an initial enquiry.\n\n## Official profiles\n\n${profiles}\n`;
export const aboutMarkdown = `# About Aashish Mahato\n\n${creativeBio}\n\nI first got hands-on with a computer in 2020 and began exploring IT, graphic design, and video editing. In 2023, I started making videos and designing LinkedIn banners and social media posters. Working with Cosmic Electrical helped sharpen my understanding of layout and visual communication.\n\nTravel brought me into filmmaking and photography, including films from Mustang and Manang. I joined Herald College Kathmandu on 17 June 2026, where I am learning web application development and exploring motion graphics through projects. My work connects visual design with practical websites and moving images.\n\n## Skills and work\n\n${services}\n\n## Official profiles\n\n${profiles}\n`;
export const privacyMarkdown = `# Privacy\n\nLast updated: ${privacyUpdated}.\n\n${privacySections.map(s => `## ${s.title}\n\n${s.text}`).join('\n\n')}\n\n## Contact and provider policies\n\n${profiles}\n${privacyProviders.map(p => `- ${link(p.label, p.url)}`).join('\n')}\n`;
export const pageMarkdown = Object.fromEntries(Object.entries(searchMeta).map(([id, [title, description, path]]) => {
  let body = `# ${title}\n\n${description}\n\n`;
  if (id === 'home') body += `${creativeBio}\n\n## Services\n\n${services}\n\n## Selected projects\n\n${projects}\n\n## Contact\n\n${link('Discuss a project', '/contact/')} through the official profiles.\n`;
  else if (id === 'about') body = aboutMarkdown;
  else if (id === 'contact') body = contactMarkdown;
  else if (id === 'privacy') body = privacyMarkdown;
  else if (id === 'work') body += `## Skills\n\n${services}\n\n## Selected projects\n\n${projects}\n`;
  else if (id === 'gallery') body += `## Visual archive\n\n${galleryMedia.map(p => `- ${link(p.title, p.src)} — ${p.category}`).join('\n')}\n\n${projects}\n`;
  else {
    const service = creativeServices.find(s => id === `skill-${s.id}`);
    body += `${service.description}\n\n${service.evidence}\n\n## Project enquiries\n\n${link('Contact Aashish', '/contact/')}\n`;
    if (service.id === 'web') body += `\n## Web projects\n\n${webProjects.map(p => `- ${p.title}: ${p.description || p.category}`).join('\n')}\n`;
  }
  body += `\n## Portfolio pages\n\n${['work', 'gallery', 'about', 'contact', 'privacy'].map(key => `- ${link(searchMeta[key][0], searchMeta[key][2])}`).join('\n')}\n`;
  return [path, body];
}));
export const agentInstructions = `# When to use this portfolio\n\nUse this site when a user wants to evaluate Aashish Mahato for filmmaking, travel video editing, portrait or landscape photography, motion graphics, branding, graphic design, interface design, or React web development, especially for projects connected to Kathmandu and Nepal.\n\n## How to use the site\n\n1. Read ${link('About', '/about/')} to verify identity and background.\n2. Read ${link('Work', '/work/')} and the relevant skill page to inspect examples. These are portfolio examples, not promises of availability or results.\n3. Use ${link('Contact', '/contact/')} to find the official Instagram and LinkedIn profiles. Share a proposed brief with the user before contacting Aashish on their behalf.\n4. Confirm scope, budget, schedule, permissions, and deliverables directly with Aashish. There is no booking, payment, or messaging API on this website.\n\nRequest public page URLs with Accept: text/markdown, or follow the index.md variants listed in ${link('llms.txt', '/llms.txt')}. Missing pages return HTTP 404 with recovery links. Do not infer prices, availability, qualifications, or clients beyond what the portfolio states.\n`;
export const llmsText = `# Aashish Mahato\n\n> Personal portfolio of a filmmaker, photographer, designer, and web developer based in Kathmandu, Nepal.\n\nThis site provides work samples and official contact profiles. It has no booking or transaction API. Public pages support Accept: text/markdown; explicit index.md versions are also available.\n\n## When to use this\n\n- ${link('Agent instructions', '/agent-instructions.md')}: Use this portfolio to evaluate Aashish for film editing, photography, branding, graphic design, motion graphics, interface design, or React websites. Read relevant examples, then use the contact profiles to discuss scope and availability with his confirmation.\n\n## Portfolio\n\n${Object.entries(searchMeta).map(([, [title, description, path]]) => `- ${link(title, `${path}index.md`)}: ${description}`).join('\n')}\n\n## Optional\n\n- ${link('Sitemap', '/sitemap.xml')}: Complete list of public HTML pages.\n`;
export const notFoundMarkdown = `# 404 — Page not found\n\nThe requested page does not exist on Aashish Mahato’s portfolio. Choose a published page from the ${link('sitemap', '/sitemap.xml')}, or read ${link('llms.txt', '/llms.txt')} for work samples and official contact information.\n`;
