export const privacyUpdated = '9 October 2026';
export const privacySections = [
  { title: 'About this website', text: 'This is the personal portfolio of Aashish Mahato, based in Kathmandu, Nepal. It presents film, photography, design, and web development work. You can browse without creating an account. The site does not have a checkout or a project enquiry form that stores submissions.' },
  { title: 'Analytics and technical information', text: 'The website includes Google Analytics and Google Tag Manager, along with Vercel Analytics and Speed Insights. These tools can receive page views, browser and device information, performance measurements, and technical request data. Google Analytics can use cookies or similar identifiers according to your browser settings and the configured Google tags. Vercel also processes request information to host, secure, and deliver this website. Google Tag Manager loads configured tags; its configuration can affect the information collected.' },
  { title: 'Media, fonts, and external links', text: 'Some videos are delivered through Cloudinary, and fonts are loaded from Google Fonts. Loading these resources sends technical requests to those providers, such as your IP address and browser headers. Links to Instagram, LinkedIn, GitHub, Facebook, YouTube, and project websites take you to external services with their own privacy policies. This portfolio does not control what those services collect.' },
  { title: 'Messages and project enquiries', text: 'Contact links open Instagram or LinkedIn. If you send a message there, Aashish receives the information you choose to share, such as your name, project brief, timeline, and contact details, and uses it to discuss or deliver the project. Avoid sending passwords, payment details, or other sensitive information in an initial enquiry. The messaging platform also processes your message under its own policies.' },
  { title: 'Your choices and privacy requests', text: 'You can limit cookies, block third-party requests, or use browser privacy controls, though some media or fonts may not load. For questions about this website or information you shared directly with Aashish, contact his official Instagram or LinkedIn profile. You can ask about access, correction, or deletion of your enquiry information. Provider-managed analytics and hosting records follow the providers’ settings and retention policies; this page does not promise a fixed retention period for those records.' },
  { title: 'Changes to this notice', text: 'This notice describes the services included in the current website code. It may be updated when the website or its services change. The date above identifies the latest revision. Refer to the linked provider policies for details of their own data handling.' },
];
export const privacyProviders = [
  { label: 'Google privacy policy', url: 'https://policies.google.com/privacy' },
  { label: 'Vercel privacy policy', url: 'https://vercel.com/legal/privacy-policy' },
  { label: 'Cloudinary privacy policy', url: 'https://cloudinary.com/privacy' },
];
